#ifndef INTERSECTION_DEF
#define INTERSECTION_DEF
enum INTERSECTION_CASE {
	INTERSECTED_ONE,
	INTERSECTED_TWO,
	NO_INTERSECTION
};
enum OBJECT_TYPE {
	SPHERE, BOX, TRIANGLE
};
#endif INTERSECTION_DEF